
class Action():
    TYPE_NONE=0
    TYPE_GOTO_X_Y=1
    TYPE_GOTO_ZONE=2
    TYPE_TAKE_OBJ=3
    TYPE_RELEASE_OBJ=4
    TYPE_MAKE=5
    TYPE_RESTORE=6
    TYPE_MAKE_VISIBLE=7
    TYPE_SET_STATUS=8
    TYPE_TASKWORK=9
    TYPE_INCREMENT_NEED=10
    TYPE_RELEASE_ZONE=11
    TYPE_PEOPLE_STATUS=12
    TYPE_RESTORE_TASK = 13
    TYPE_TASKWORK_OBJ =14
    TYPE_TURN_INTO_GARBAGE = 15
    TYPE_LIFT_OBJ = 16
    TYPE_PUTDOWN_OBJ = 17
    TYPE_GOTO_MACHINE_TYPE =18
    TYPE_CREATE_MACHINE_OBJ_ASSIGN = 19
    TYPE_LAUCH_OBJ_TASK = 20
    TYPE_GOTO_OBJ = 21
    TYPE_LOCKED_MACHINE = 22
    def __init__(self,type,x,y):
        pass
