
class Action():
    TYPE_NONE=0
    TYPE_GOTO_X_Y=1
    TYPE_GOTO_ZONE=2
    TYPE_TAKE_OBJ=3
    TYPE_RELEASE_OBJ=4
    TYPE_MAKE=5
    TYPE_RESTORE=6
    TYPE_MAKE_VISIBLE=7
    TYPE_SET_STATUS=8
    TYPE_TASKWORK=9
    TYPE_INCREMENT_NEED=10
    TYPE_RELEASE_ZONE=11
    TYPE_PEOPLE_STATUS=12
    TYPE_RESTORE_TASK = 13
    TYPE_TASKWORK_OBJ =14
    TYPE_TURN_INTO_GARBAGE = 15
    def __init__(self,type,x,y):
        pass
